let latestPrefs=null;
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function setStatus(message,type=''){const el=document.getElementById('status');el.textContent=message;el.className='status '+type}
function createGroup(){const name=document.getElementById('group').value.trim();if(!name){alert('Enter a group name.');return;}const code=makeCode();localStorage.setItem('group_'+code,JSON.stringify({name,members:[]}));document.getElementById('code').textContent=code;document.getElementById('joinCode').value=code;document.getElementById('created').classList.remove('hidden')}
function useLocation(){const help=document.getElementById('locationHelp');if(!navigator.geolocation){help.textContent='Location is not supported by this browser. Please type your starting location.';return;}help.textContent='Requesting location permission…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude.toFixed(5),lon=pos.coords.longitude.toFixed(5);document.getElementById('location').value=`${lat}, ${lon}`;document.getElementById('location').dataset.lat=lat;document.getElementById('location').dataset.lon=lon;help.textContent='Current coordinates added. You can replace them with a typed location if preferred.'},()=>{help.textContent='Location permission was denied or unavailable. Please type your starting location instead.'},{enableHighAccuracy:false,timeout:8000,maximumAge:300000})}
function collectPrefs(){const start=document.getElementById('startDate').value,end=document.getElementById('endDate').value;const location=document.getElementById('location');return {inviteCode:document.getElementById('joinCode').value.trim().toUpperCase(),name:document.getElementById('name').value.trim(),budget:document.getElementById('budget').value,activity:document.getElementById('activity').value.trim(),startDate:start,endDate:end,location:location.value.trim(),latitude:location.dataset.lat||null,longitude:location.dataset.lon||null,maxDistance:Number(document.getElementById('distance').value),distanceUnit:document.getElementById('distanceUnit').value}}
function validate(p){if(!p.inviteCode)return 'Enter the group invite code.';if(!p.name)return 'Enter your name.';if(!p.budget)return 'Select a budget.';if(!p.activity)return 'Enter at least one interest or activity.';if(!p.startDate||!p.endDate)return 'Select both availability dates.';if(p.endDate<p.startDate)return 'The end date cannot be before the start date.';if(!p.location)return 'Enter a starting location or use Current Location.';if(!Number.isFinite(p.maxDistance)||p.maxDistance<=0)return 'Enter a travel distance greater than 0.';return ''}
function savePrefs(){const p=collectPrefs(),problem=validate(p);if(problem){setStatus(problem,'error');return;}const raw=localStorage.getItem('group_'+p.inviteCode);if(!raw){setStatus('Group not found in this browser. Check the invite code. Shared codes will require the team database integration.','error');return;}const data=JSON.parse(raw);data.members.push(p);localStorage.setItem('group_'+p.inviteCode,JSON.stringify(data));latestPrefs=p;setStatus(`Preferences saved for ${p.name} in ${data.name}.`,'success')}
function prepareResults(){const err=document.getElementById('resultError');err.textContent='';const p=latestPrefs||collectPrefs(),problem=validate(p);if(problem){err.textContent='Complete the preference form first: '+problem;return;}const raw=localStorage.getItem('group_'+p.inviteCode);if(!raw){err.textContent='The group cannot be found in this browser. Shared storage integration is still required.';return;}const data=JSON.parse(raw);const summary={group:data.name,memberCount:data.members.length,location:p.location,availability:{from:p.startDate,to:p.endDate},maxDistance:p.maxDistance,distanceUnit:p.distanceUnit,budget:p.budget,interests:p.activity};document.getElementById('requestSummary').textContent=`${data.name} has ${data.members.length} saved member preference set(s). The frontend can now send the structured request to the AI service.`;document.getElementById('requestTags').innerHTML=[`Budget: ${p.budget==='100+'?'$100+':'up to $'+p.budget}`,`Interest: ${p.activity}`,`Dates: ${p.startDate} → ${p.endDate}`,`Location: ${p.location}`,`Travel: ${p.maxDistance} ${p.distanceUnit}`].map(x=>`<span class="tag">${escapeHtml(x)}</span>`).join('');document.getElementById('results').classList.remove('hidden');console.log('AI integration payload',summary)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
